# Generated by Django 5.2.8 on 2025-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="allowed_companies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Companies allowed to view this private contract",
                related_name="allowed_contracts",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=20,
            ),
        ),
    ]
