# Generated by Django 5.2.6 on 2025-11-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_allowed_companies_contract_visibility"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="stored_object",
        ),
        migrations.AddField(
            model_name="contract",
            name="owner_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="second_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="second_party_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_CONFIRMATION", "Pending Confirmation"),
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="contracts.contract",
                    ),
                ),
                (
                    "stored_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="storage.storedobject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("contract", "stored_object")},
            },
        ),
    ]
