# Generated by Django 5.2.8 on 2025-11-08 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attestation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payload", models.JSONField()),
                ("signature_b64", models.TextField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="requests_app.dataaccessrequest",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed_attestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
